name: Update Dashboard and Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * 1-5'  # 4PM IST on weekdays

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python source.py

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # or the folder where index.html is

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
