name: Update Dashboard

on:
  schedule:
    - cron: '30 10 * * *'  # Runs daily at 10:30 UTC (which is 4 PM IST)
  workflow_dispatch:        # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run portfolio script
      run: python source.py
        
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/sm-thamizha/pnl-dashboard-trial.git
        git add index.html
        git commit -m "Auto update dashboard" || echo "No changes to commit"
        git push
